### ISSUE TITLE
[TASK] - Bekijken of dit steeds in form moet zitten

### ISSUE THREAD

**Issue by driesva** [milieuinfo/webcomponent-vl-ui-search#1]
**Beschrijving**
De huidige implementatie naar analogie met de Webuniversum voorbeelden https://overheid.vlaanderen.be/webuniversum/v3/documentation/components/vl-ui-search/ gebruikt geen form. Indien je echter dieper kijkt in de HTML code van de voorbeelden wordt deze component in een form gebruikt. 

Dit betekent dat de submit functionaliteit door de browser wordt voorzien en dat een eigen implementatie misschien niet nodig is.
Ook zou dit een enabler kunnen zijn voor form validation van het input field.

Te onderzoeken of deze component steeds in een form moet worden gebruikt, deze zelf een form voorziet of hybride kan zijn. 

**Extra info**
Een echt voorbeeld: https://www.vlaanderen.be/zoek

(Merk ook de _NaN - NaN van 0_ op )

**Comment by kevcraey** [comment]
https://www.milieuinfo.be/jira/browse/UIG-2208
