### ISSUE TITLE
[FEATURE] - Indicatie geven dat zoekopdracht lopend is

### ISSUE THREAD

**Issue by driesva** [milieuinfo/webcomponent-vl-ui-search#2]
**Wat moet er gebeuren**
Als er nu wordt geklikt, blijft de zoek knop actief en is er geen enkele indicatie dat een zoekopdracht gelanceerd werd. Als het resultaat niet onmiddellijk zichtbaar is, zou de gebruiker meerdere keren kunnen zoeken...

Misschien moet de vl-ui-search standaard de zoek knop disablen en een loading button tonen (wanneer niet inline).
Een voorbeeld:
![image](https://user-images.githubusercontent.com/29454303/74835686-2d28e300-531e-11ea-816d-56d9ceecf3a5.png)

Uiteraard moet er een functie zijn om te resetten zodat de afnemer dit kan aanroepen wanneer het zoeken gedaan is.

Ook het zoekveld zelf moet misschien gedisabled worden, als dit vanuit UX een best practice is.

Merk op dat vb Google dit niet doet, maar het zoeken is dan ook super snel... In ons geval waarbij we data bij MAGDA ophalen blijkt dit niet zo te zijn.

**Comment by kevcraey** [comment]
https://www.milieuinfo.be/jira/browse/UIG-2209
