### ISSUE TITLE
[BUG] - inline search heeft geen kader rond input in Safari

### ISSUE THREAD

**Issue by driesva** [milieuinfo/webcomponent-vl-ui-search#38]
**Omschrijf het probleem**
Bij het nakijken van onze applicatie had ik gemerkt dat er geen kader is rond de input van de map search in Safari. Het probleem zit eigenlijk al in de vl-ui-search.
Het is ook zichtbaar op [de demo pagina](https://webcomponenten.omgeving.vlaanderen.be/demo/vl-search.html), maar niet bij [Webuniversum](https://overheid.vlaanderen.be/webuniversum/v3/documentation/components/vl-ui-search/), al is het gebruikte icoon daar wel verschillend.

**Screenshots**
In Safari:
<img width="861" alt="image" src="https://user-images.githubusercontent.com/29454303/103283694-8f8c4e80-49d9-11eb-977d-7219583bf7c2.png">

In Fx:
![image](https://user-images.githubusercontent.com/29454303/103283713-9a46e380-49d9-11eb-83aa-e48d74438c10.png)

Op Webuniversum met Safari
<img width="847" alt="image" src="https://user-images.githubusercontent.com/29454303/103283748-a9c62c80-49d9-11eb-87a5-51ca914d550e.png">

**Omgeving (gelieve aan te vullen):**
 - Browser Safari Version 14.0.2 (16610.3.7.1.9)
 - Versie component 1.1.4

**Comment by coemans** [comment]
Probleem is in de huidige versie niet meer reproduceerbaar. Als het alsnog een probleem blijkt mag het issue opnieuw geopend worden.
